// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var $$Node = require("../bindings/Node.bs.js");

function run(p, file) {
  return $$Node.ChildProcess.exec("unzip " + (String(file) + ""), p !== undefined ? ({
                  cwd: p
                }) : { });
}

exports.run = run;
/* Node Not a pure module */
