sudo: required
language: generic

scripts:
  - &opam
    before_install:
      - '[ "$TRAVIS_EVENT_TYPE" != cron ] || rm -rf ~/.opam ./_opam ./node_modules'

    install:
      - mkdir -p _cache
      - |
        case $TRAVIS_OS_NAME in
          "linux") OPAM_OS=linux;;
          "osx") OPAM_OS=macos;;
        esac
      - OPAM_VERSION=2.0.5
      - OPAM_PKG=opam-${OPAM_VERSION}-x86_64-${OPAM_OS}
      - |
        if [ ! -f _cache/opam ]
        then
          wget https://github.com/ocaml/opam/releases/download/${OPAM_VERSION}/${OPAM_PKG}
          mv ${OPAM_PKG} _cache/opam
        fi
      - sudo cp _cache/opam /usr/local/bin/opam
      - sudo chmod a+x /usr/local/bin/opam

      - opam init -y --bare --disable-sandboxing --disable-shell-hook
      - OPAM_FROM_CACHE=YES
      - |
        if [ ! -d _opam/bin ]
        then
          OPAM_FROM_CACHE=NO
          rm -rf _opam
          opam switch create . $COMPILER $REPOSITORIES --no-install
        fi
      - eval `opam config env`
      - ocaml -version
      - opam --version

      - |
        if [ "$OPAM_FROM_CACHE" == NO ]
        then
          opam install -y --deps-only .
        fi

    script:
      - |
        if [ -d _cache/_build ]
        then
          cp -r _cache/_build .
        fi
      - npm --version
      - npm i
      - npm run compile
      - |
        if [ ! -d _cache/_build ]
        then
          cp -r _build _cache
        fi

    before_cache:
      - opam clean

matrix:
  include:
    - <<: *opam
      os: osx
      env: COMPILER=4.09.0
    - <<: *opam
      os: linux
      env: COMPILER=4.09.0

  fast_finish: true

cache:
  directories:
    - $HOME/.opam
    - ./_opam
    - ./node_modules
    - ./_cache

