// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Vscode = require("vscode");
var ProjectType = require("../ProjectType.bs.js");

function getFullTextRange($$document) {
  var firstLine = Curry._1($$document.lineAt, 0);
  var lastLine = Curry._1($$document.lineAt, $$document.lineCount - 1 | 0);
  return new Vscode.Range(0, firstLine.range.start.character, $$document.lineCount - 1 | 0, lastLine.range.end.character);
}

function getFormatterPath(formatter) {
  var rootPath = Vscode.workspace.rootPath;
  return ProjectType.detect(rootPath).then((function (param) {
                if (param.tag) {
                  return Promise.resolve(/* Error */Block.__(1, [ProjectType.E.toString(param[0])]));
                } else {
                  var esy = process.platform === "win32" ? "esy.cmd" : "esy";
                  var tmp = param[0];
                  if (typeof tmp === "number") {
                    return Promise.resolve(/* Ok */Block.__(0, ["opam exec -- " + (String(formatter) + "")]));
                  } else if (tmp.tag) {
                    return Promise.resolve(/* Ok */Block.__(0, ["" + (String(esy) + (" -P " + (String(rootPath) + ("/.vscode/esy " + (String(formatter) + "")))))]));
                  } else {
                    return Promise.resolve(/* Ok */Block.__(0, ["" + (String(esy) + (" " + (String(formatter) + "")))]));
                  }
                }
              }));
}

var P = /* alias */0;

exports.P = P;
exports.getFullTextRange = getFullTextRange;
exports.getFormatterPath = getFormatterPath;
/* vscode Not a pure module */
