// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Os = require("os");
var $$Node = require("../bindings/Node.bs.js");
var Path = require("path");
var Curry = require("bs-platform/lib/js/curry.js");
var Vscode = require("vscode");
var V4 = require("uuid/v4");
var FormatterUtils = require("./FormatterUtils.bs.js");
var Caml_builtin_exceptions = require("bs-platform/lib/js/caml_builtin_exceptions.js");

function register(param) {
  Vscode.languages.registerDocumentFormattingEditProvider({
        scheme: "file",
        language: "ocaml"
      }, {
        provideDocumentFormattingEdits: (function ($$document) {
            var filePath = $$document.fileName;
            var fileName = Path.basename($$document.fileName);
            var cwd = Path.dirname($$document.fileName);
            var match = Vscode.window.activeTextEditor;
            if (match !== undefined) {
              var textEditor = match;
              var id = V4();
              var tempFileName = Path.join(Os.tmpdir(), "vscode-merlin-ocamlformat-" + (String(id) + ("-" + (String(fileName) + ""))));
              return $$Node.Fs.writeFile(tempFileName, Curry._1(textEditor.document.getText, /* () */0)).then((function (param) {
                                  return FormatterUtils.getFormatterPath("ocamlformat");
                                })).then((function (param) {
                                if (param.tag) {
                                  return Promise.reject([
                                              Caml_builtin_exceptions.failure,
                                              "Could not setup ocamlformat: " + param[0]
                                            ]);
                                } else {
                                  return $$Node.ChildProcess.exec("" + (String(param[0]) + (" --enable-outside-detected-project --name=" + (String(filePath) + (" " + (String(tempFileName) + ""))))), {
                                              cwd: cwd
                                            });
                                }
                              })).then((function (param) {
                              if (param.tag) {
                                return Promise.reject([
                                            Caml_builtin_exceptions.failure,
                                            "Could not run ocamlfmt: " + Curry._1($$Node.ChildProcess.E.toString, param[0])
                                          ]);
                              } else {
                                var textRange = FormatterUtils.getFullTextRange(textEditor.document);
                                $$Node.Fs.unlink(tempFileName);
                                return Promise.resolve([Vscode.TextEdit.replace(textRange, param[0][1])]);
                              }
                            })).catch((function (e) {
                            $$Node.Fs.unlink(tempFileName);
                            var message = $$Node.$$Error.ofPromiseError(e);
                            return Vscode.window.showErrorMessage("Error: " + (String(message) + ""));
                          }));
            } else {
              return Promise.resolve([]);
            }
          })
      });
  return /* () */0;
}

var P = /* alias */0;

exports.P = P;
exports.register = register;
/* os Not a pure module */
