// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Rimraf = require("rimraf");

function run(p) {
  return new Promise((function (resolve, param) {
                Rimraf(p, (function (err) {
                        if (err == null) {
                          return resolve(/* Ok */Block.__(0, [/* () */0]));
                        } else {
                          return resolve(/* Error */Block.__(1, [/* () */0]));
                        }
                      }));
                return /* () */0;
              }));
}

var Rimraf$1 = {
  run: run
};

exports.Rimraf = Rimraf$1;
/* rimraf Not a pure module */
