// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.js");
var $$Node = require("../bindings/Node.bs.js");

Jest.describe("Expect", (function (param) {
        return Jest.testPromise("toBe", undefined, (function (param) {
                      return $$Node.ChildProcess.exec("echo hey", { }).then((function (param) {
                                    if (param.tag) {
                                      return Promise.resolve(Jest.fail("exec should have succeeded"));
                                    } else {
                                      return Promise.resolve(Jest.Expect.toContainString("hey", Jest.Expect.expect(param[0][1])));
                                    }
                                  }));
                    }));
      }));

/*  Not a pure module */
