joo_global_object.__LIB__NODE__IMPORTS = {
  assert: require("assert"),
  async_hooks: require("async_hooks"),
  buffer: require("buffer"),
  child_process: require("child_process"),
  cluster: require("cluster"),
  console: require("console"),
  constants: require("constants"),
  crypto: require("crypto"),
  dgram: require("dgram"),
  dns: require("dns"),
  domain: require("domain"),
  events: require("events"),
  fs: require("fs"),
  fsPromises: require("fs").promises,
  http: require("http"),
  http2: require("http2"),
  https: require("https"),
  inspector: require("inspector"),
  module: require("module"),
  net: require("net"),
  os: require("os"),
  path: require("path"),
  perf_hooks: require("perf_hooks"),
  process: require("process"),
  punycode: require("punycode"),
  querystring: require("querystring"),
  readline: require("readline"),
  repl: require("repl"),
  stream: require("stream"),
  string_decoder: require("string_decoder"),
  timers: require("timers"),
  tls: require("tls"),
  // trace_events: require("trace_events"),
  tty: require("tty"),
  url: require("url"),
  util: require("util"),
  v8: require("v8"),
  vm: require("vm"),
  // wasi: require("wasi"),
  worker_threads: require("worker_threads"),
  zlib: require("zlib"),
};
