// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Belt_Option = require("bs-platform/lib/js/belt_Option.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");

function $pipe$bang(o, f) {
  if (o !== undefined) {
    return /* () */0;
  } else {
    return Curry._1(f, /* () */0);
  }
}

function toResult(e, param) {
  if (param !== undefined) {
    return /* Ok */Block.__(0, [Caml_option.valFromOption(param)]);
  } else {
    return /* Error */Block.__(1, [e]);
  }
}

function toPromise(e, param) {
  if (param !== undefined) {
    return Caml_option.valFromOption(param);
  } else {
    return Promise.resolve(/* Error */Block.__(1, [e]));
  }
}

var $great$great$eq = Belt_Option.flatMap;

var $great$great$pipe = Belt_Option.map;

exports.$great$great$eq = $great$great$eq;
exports.$great$great$pipe = $great$great$pipe;
exports.$pipe$bang = $pipe$bang;
exports.toResult = toResult;
exports.toPromise = toPromise;
/* No side effect */
