// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Sys = require("bs-platform/lib/js/sys.js");
var Json = require("@glennsl/bs-json/src/Json.bs.js");
var $$Node = require("./bindings/Node.bs.js");
var Path = require("path");
var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Setup = require("./Setup.bs.js");
var Utils = require("./Utils.bs.js");
var Result = require("./Result.bs.js");
var Vscode = require("vscode");
var Js_dict = require("bs-platform/lib/js/js_dict.js");
var Caml_obj = require("bs-platform/lib/js/caml_obj.js");
var Filename = require("bs-platform/lib/js/filename.js");
var Tablecloth = require("./tablecloth/bs/src/tablecloth.bs.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");
var Json_decode = require("@glennsl/bs-json/src/Json_decode.bs.js");

function setupWithProgressIndicator(m, folder) {
  return Vscode.window.withProgress({
              location: 15,
              title: "Setting up toolchain..."
            }, (function (progress) {
                var succeeded = {
                  contents: /* Ok */Block.__(0, [/* () */0])
                };
                var eventEmitter = Curry._1(m.make, /* () */0);
                Curry._2(m.onProgress, eventEmitter, (function (percent) {
                        console.log("Percentage:", percent);
                        return progress.report({
                                    increment: percent * 100 | 0
                                  });
                      }));
                Curry._2(m.onEnd, eventEmitter, (function (param) {
                        return progress.report({
                                    increment: 100
                                  });
                      }));
                Curry._2(m.onError, eventEmitter, (function (errorMsg) {
                        succeeded.contents = /* Error */Block.__(1, [errorMsg]);
                        return /* () */0;
                      }));
                return Curry._2(m.run, eventEmitter, folder).then((function (param) {
                              return Promise.resolve(succeeded.contents);
                            }));
              }));
}

function make(env, cmd) {
  var cmd$1 = Sys.unix ? cmd : cmd + ".cmd";
  var match = Js_dict.get(env, "PATH");
  if (match !== undefined) {
    return Promise.all(Tablecloth.$$Array.fromList(Tablecloth.$$String.split(Utils.env_sep, match)).map((function (p) {
                          return $$Node.Fs.exists(Filename.concat(p, cmd$1));
                        }))).then((function (param) {
                    return Utils.$less$less((function (prim) {
                                  return Promise.resolve(prim);
                                }), (function (param) {
                                  return param.filter((function (x) {
                                                return x;
                                              }));
                                }), param);
                  })).then((function (param) {
                  return Utils.$less$less((function (prim) {
                                return Promise.resolve(prim);
                              }), (function (l) {
                                var match = l.length === 0;
                                if (match) {
                                  return /* Error */Block.__(1, [" Command \"" + (String(cmd$1) + "\" not found ")]);
                                } else {
                                  return /* Ok */Block.__(0, [{
                                              cmd: cmd$1,
                                              env: env
                                            }]);
                                }
                              }), param);
                }));
  } else {
    return Promise.resolve(/* Error */Block.__(1, ["'PATH' variable not found in the environment"]));
  }
}

function output(args, cwd, param) {
  var cmd = param.cmd;
  var shellString = /* array */[cmd].concat(args).join(" ");
  console.log(shellString);
  return $$Node.ChildProcess.exec(shellString, {
                cwd: cwd,
                env: param.env
              }).then((function (param) {
                return Utils.$less$less((function (prim) {
                              return Promise.resolve(prim);
                            }), (function (param) {
                              if (param.tag) {
                                return Result.fail(Curry._1($$Node.ChildProcess.E.toString, param[0]));
                              } else {
                                var match = param[0];
                                var exitCode = match[0];
                                if (exitCode === 0) {
                                  return /* Ok */Block.__(0, [match[1]]);
                                } else {
                                  return /* Error */Block.__(1, [" Command " + (String(cmd) + (" failed:\nexitCode: " + (String(exitCode) + ("\nstderr: " + (String(match[2]) + "\n")))))]);
                                }
                              }
                            }), param);
              }));
}

var name = "esy";

var lockFile = Utils.Fpath.$slash(Utils.Fpath.v("esy.lock"), "index.json");

function make$1(env, root, discoveredManifestPath) {
  return Utils.okThen((function (cmd) {
                  return Result.$$return({
                              cmd: cmd,
                              lsp: (function (param) {
                                  return /* tuple */[
                                          name,
                                          /* array */[
                                            "-P",
                                            Utils.Fpath.toString(root),
                                            "ocamllsp"
                                          ]
                                        ];
                                }),
                              env: (function (param) {
                                  return Utils.okThen((function (stdout) {
                                                  var match = Json.parse(stdout);
                                                  if (match !== undefined) {
                                                    return Result.$$return(Json_decode.dict(Json_decode.string, Caml_option.valFromOption(match)));
                                                  } else {
                                                    return /* Error */Block.__(1, ["'esy command-env' returned non-json output: " + stdout]);
                                                  }
                                                }))(output(/* array */[
                                                  "command-env",
                                                  "--json",
                                                  "-P",
                                                  Utils.Fpath.toString(root)
                                                ], Utils.Fpath.toString(root), cmd));
                                }),
                              setup: (function (param) {
                                  var rootStr = Utils.Fpath.toString(root);
                                  return output(/* array */[
                                                  "status",
                                                  "-P",
                                                  rootStr
                                                ], rootStr, cmd).then((function (param) {
                                                  return Utils.$less$less((function (prim) {
                                                                return Promise.resolve(prim);
                                                              }), (function (param) {
                                                                if (param.tag) {
                                                                  return Result.$$return(false);
                                                                } else {
                                                                  var match = Json.parse(param[0]);
                                                                  if (match !== undefined) {
                                                                    return Result.$$return(Json_decode.field("isProjectReadyForDev", Json_decode.bool, Caml_option.valFromOption(match)));
                                                                  } else {
                                                                    return Result.$$return(false);
                                                                  }
                                                                }
                                                              }), param);
                                                })).then((function (param) {
                                                if (param.tag) {
                                                  return Promise.resolve(Result.fail(param[0]));
                                                } else if (param[0]) {
                                                  return Promise.resolve(Result.$$return(/* () */0));
                                                } else if (Caml_obj.caml_equal(root, discoveredManifestPath)) {
                                                  return setupWithProgressIndicator({
                                                              make: Setup.Esy.make,
                                                              onProgress: Setup.Esy.onProgress,
                                                              onEnd: Setup.Esy.onEnd,
                                                              onError: Setup.Esy.onError,
                                                              reportProgress: Setup.Esy.reportProgress,
                                                              reportEnd: Setup.Esy.reportEnd,
                                                              reportError: Setup.Esy.reportError,
                                                              run: Setup.Esy.run
                                                            }, rootStr);
                                                } else {
                                                  return setupWithProgressIndicator({
                                                              make: Setup.Bsb.make,
                                                              onProgress: Setup.Bsb.onProgress,
                                                              onEnd: Setup.Bsb.onEnd,
                                                              onError: Setup.Bsb.onError,
                                                              reportProgress: Setup.Bsb.reportProgress,
                                                              reportEnd: Setup.Bsb.reportEnd,
                                                              reportError: Setup.Bsb.reportError,
                                                              run: Setup.Bsb.run
                                                            }, Utils.Fpath.toString(discoveredManifestPath));
                                                }
                                              }));
                                })
                            });
                }))(make(env, "esy"));
}

var name$1 = "opam";

var lockFile$1 = Utils.Fpath.v("opam.lock");

function make$2(env, root, param) {
  var rootStr = Utils.Fpath.toString(root);
  return Utils.okThen((function (cmd) {
                  return Result.$$return({
                              cmd: cmd,
                              lsp: (function (param) {
                                  return /* tuple */[
                                          name$1,
                                          /* array */[
                                            "exec",
                                            "ocamllsp"
                                          ]
                                        ];
                                }),
                              env: (function (param) {
                                  return Utils.okThen((function (stdout) {
                                                  return Result.$$return(Js_dict.fromList(Tablecloth.List.foldLeft((function (kv, acc) {
                                                                        if (kv.tag) {
                                                                          console.log(kv[0]);
                                                                          return acc;
                                                                        } else {
                                                                          return /* :: */[
                                                                                  kv[0],
                                                                                  acc
                                                                                ];
                                                                        }
                                                                      }), /* [] */0, Tablecloth.List.map((function (l) {
                                                                            if (l) {
                                                                              var match = l[1];
                                                                              if (match && !match[1]) {
                                                                                return /* Ok */Block.__(0, [/* tuple */[
                                                                                            l[0],
                                                                                            match[0]
                                                                                          ]]);
                                                                              } else {
                                                                                console.log(l);
                                                                                return /* Error */Block.__(1, ["Splitting on '=' in env output returned more than two items"]);
                                                                              }
                                                                            } else {
                                                                              return /* Error */Block.__(1, ["Splitting on '=' in env output failed"]);
                                                                            }
                                                                          }), Tablecloth.List.map((function (x) {
                                                                                return Tablecloth.$$String.split("=", x);
                                                                              }), Tablecloth.$$String.split("\n", stdout))))));
                                                }))(output(/* array */[
                                                  "exec",
                                                  "env"
                                                ], Utils.Fpath.toString(root), cmd));
                                }),
                              setup: (function (param) {
                                  return setupWithProgressIndicator({
                                              make: Setup.Opam.make,
                                              onProgress: Setup.Opam.onProgress,
                                              onEnd: Setup.Opam.onEnd,
                                              onError: Setup.Opam.onError,
                                              reportProgress: Setup.Opam.reportProgress,
                                              reportEnd: Setup.Opam.reportEnd,
                                              reportError: Setup.Opam.reportError,
                                              run: Setup.Opam.run
                                            }, rootStr);
                                })
                            });
                }))(make(env, "opam"));
}

function ofName(env, name$2, root, discoveredManifestPath) {
  if (name$2 === name$1) {
    return make$2(env, root, discoveredManifestPath);
  } else if (name$2 === name) {
    return make$1(env, root, discoveredManifestPath);
  } else {
    return Promise.resolve(Result.fail("Invalid package manager name"));
  }
}

function alreadyUsed(folder) {
  return Promise.all(Tablecloth.$$Array.map((function (pm) {
                      var lockFileFpath = pm ? Utils.Fpath.join(folder, lockFile) : Utils.Fpath.join(folder, lockFile$1);
                      return $$Node.Fs.exists(Utils.Fpath.show(lockFileFpath)).then((function (param) {
                                    return Utils.$less$less((function (prim) {
                                                  return Promise.resolve(prim);
                                                }), (function (exists) {
                                                  return /* tuple */[
                                                          pm,
                                                          exists
                                                        ];
                                                }), param);
                                  }));
                    }), Tablecloth.$$Array.fromList(/* :: */[
                        /* Esy */1,
                        /* :: */[
                          /* Opam */0,
                          /* [] */0
                        ]
                      ]))).then((function (l) {
                return Promise.resolve(Result.$$return(Tablecloth.$$Array.toList(Tablecloth.$$Array.map((function (t) {
                                          return t[0];
                                        }), Tablecloth.$$Array.filter((function (param) {
                                              return param[1];
                                            }), l)))));
              }));
}

function available(env) {
  return Promise.all(Tablecloth.$$Array.fromList(Tablecloth.List.map((function (pm) {
                          var name$2 = pm ? name : name$1;
                          return make(env, name$2).then((function (param) {
                                        return Utils.$less$less((function (prim) {
                                                      return Promise.resolve(prim);
                                                    }), (function (param) {
                                                      if (param.tag) {
                                                        return /* tuple */[
                                                                pm,
                                                                false
                                                              ];
                                                      } else {
                                                        return /* tuple */[
                                                                pm,
                                                                true
                                                              ];
                                                      }
                                                    }), param);
                                      }));
                        }), /* :: */[
                        /* Esy */1,
                        /* :: */[
                          /* Opam */0,
                          /* [] */0
                        ]
                      ]))).then((function (param) {
                return Utils.$less$less((function (param) {
                              return Utils.$less$less((function (param) {
                                            return Utils.$less$less((function (param) {
                                                          return Utils.$less$less((function (prim) {
                                                                        return Promise.resolve(prim);
                                                                      }), Result.$$return, param);
                                                        }), Tablecloth.$$Array.toList, param);
                                          }), (function (param) {
                                            return Tablecloth.$$Array.map((function (t) {
                                                          return t[0];
                                                        }), param);
                                          }), param);
                            }), (function (param) {
                              return Tablecloth.$$Array.filter((function (param) {
                                            return param[1];
                                          }), param);
                            }), param);
              }));
}

function lookup(projectRoot) {
  return $$Node.Fs.readDir(Utils.Fpath.toString(projectRoot)).then((function (param) {
                if (param.tag) {
                  return Promise.resolve(/* Error */Block.__(1, [param[0]]));
                } else {
                  return Promise.all(param[0].map((function (param) {
                                      var projectRoot$1 = projectRoot;
                                      var file = param;
                                      switch (file) {
                                        case "esy.json" :
                                            return Promise.resolve(/* tuple */[
                                                        /* Esy */1,
                                                        projectRoot$1
                                                      ]);
                                        case "opam" :
                                            return $$Node.Fs.stat(Utils.Fpath.toString(Utils.Fpath.$slash(projectRoot$1, "opam"))).then((function (param) {
                                                          return Utils.$less$less((function (prim) {
                                                                        return Promise.resolve(prim);
                                                                      }), (function (param) {
                                                                        if (param.tag) {
                                                                          return ;
                                                                        } else {
                                                                          var match = param[0].isDirectory();
                                                                          if (match) {
                                                                            return ;
                                                                          } else {
                                                                            return /* tuple */[
                                                                                    /* Opam */0,
                                                                                    projectRoot$1
                                                                                  ];
                                                                          }
                                                                        }
                                                                      }), param);
                                                        }));
                                        case "package.json" :
                                            var manifestFile = Utils.Fpath.show(Utils.Fpath.$slash(projectRoot$1, "package.json"));
                                            return $$Node.Fs.readFile(manifestFile).then((function (manifest) {
                                                          var match = Json.parse(manifest);
                                                          if (match !== undefined) {
                                                            var json = Caml_option.valFromOption(match);
                                                            if (Utils.propertyExists(json, "dependencies") || Utils.propertyExists(json, "devDependencies")) {
                                                              if (Utils.propertyExists(json, "esy")) {
                                                                return Promise.resolve(/* tuple */[
                                                                            /* Esy */1,
                                                                            projectRoot$1
                                                                          ]);
                                                              } else {
                                                                return Promise.resolve(/* tuple */[
                                                                            /* Esy */1,
                                                                            Utils.Fpath.$slash(Utils.Fpath.$slash(projectRoot$1, ".vscode"), "esy")
                                                                          ]);
                                                              }
                                                            } else {
                                                              return Promise.resolve(undefined);
                                                            }
                                                          } else {
                                                            return Promise.resolve(undefined);
                                                          }
                                                        }));
                                        default:
                                          var manifestFile$1 = Utils.Fpath.show(Utils.Fpath.$slash(projectRoot$1, file));
                                          var match = Path.extname(file);
                                          switch (match) {
                                            case ".json" :
                                                return $$Node.Fs.readFile(manifestFile$1).then((function (manifest) {
                                                              var match = Json.parse(manifest);
                                                              if (match !== undefined) {
                                                                var json = Caml_option.valFromOption(match);
                                                                if (Utils.propertyExists(json, "dependencies") || Utils.propertyExists(json, "devDependencies")) {
                                                                  return Promise.resolve(/* tuple */[
                                                                              /* Esy */1,
                                                                              projectRoot$1
                                                                            ]);
                                                                } else {
                                                                  return Promise.resolve(undefined);
                                                                }
                                                              } else {
                                                                console.log("Invalid JSON file found. Ignoring...", manifest, manifestFile$1);
                                                                return Promise.resolve(undefined);
                                                              }
                                                            }));
                                            case ".opam" :
                                                return $$Node.Fs.readFile(manifestFile$1).then((function (param) {
                                                              if (param === "") {
                                                                return Promise.resolve(undefined);
                                                              } else {
                                                                return Promise.resolve(/* tuple */[
                                                                            /* Opam */0,
                                                                            projectRoot$1
                                                                          ]);
                                                              }
                                                            }));
                                            default:
                                              return Promise.resolve(undefined);
                                          }
                                      }
                                    }))).then((function (l) {
                                return Promise.resolve(/* Ok */Block.__(0, [Tablecloth.$$Array.toList(l.reduce((function (acc, x) {
                                                          return (
                                                                    x !== undefined ? Tablecloth.$$Array.fromList(/* :: */[
                                                                            x,
                                                                            /* [] */0
                                                                          ]) : Tablecloth.$$Array.empty
                                                                  ).concat(acc);
                                                        }), Tablecloth.$$Array.empty))]));
                              }));
                }
              }));
}

function init(env, folder) {
  var projectRoot = Utils.Fpath.ofString(folder);
  return Utils.okThen((function (spec) {
                  return /* Ok */Block.__(0, [{
                              spec: spec,
                              projectRoot: projectRoot
                            }]);
                }))(Promise.all(/* tuple */[
                    available(env),
                    alreadyUsed(projectRoot).then((function (param) {
                            if (param.tag) {
                              return Promise.resolve(/* Error */Block.__(1, [param[0]]));
                            } else {
                              var packageManagersInUse = param[0];
                              if (packageManagersInUse) {
                                return Promise.resolve(Result.$$return(Tablecloth.List.map((function (x) {
                                                      return /* tuple */[
                                                              x,
                                                              projectRoot
                                                            ];
                                                    }), packageManagersInUse)));
                              } else {
                                return Utils.okThen((function (packageManagersInUse) {
                                                if (packageManagersInUse) {
                                                  return Result.$$return(packageManagersInUse);
                                                } else {
                                                  return /* Error */Block.__(1, ["TODO: global toolchain"]);
                                                }
                                              }))(lookup(projectRoot));
                              }
                            }
                          }))
                  ]).then((function (param) {
                    var alreadyUsedPackageManagers = param[1];
                    var availablePackageManagers = param[0];
                    var availablePackageManagers$1;
                    if (availablePackageManagers.tag) {
                      console.log("Error during availablePackageManagers()", availablePackageManagers[0]);
                      availablePackageManagers$1 = /* [] */0;
                    } else {
                      availablePackageManagers$1 = availablePackageManagers[0];
                    }
                    var alreadyUsedPackageManagers$1;
                    if (alreadyUsedPackageManagers.tag) {
                      console.log("Error during alreadyUsedPackageManagers()", alreadyUsedPackageManagers[0]);
                      alreadyUsedPackageManagers$1 = /* [] */0;
                    } else {
                      alreadyUsedPackageManagers$1 = alreadyUsedPackageManagers[0];
                    }
                    var _multipleChoices = Tablecloth.List.filter((function (param) {
                            var x = param[0];
                            return Tablecloth.List.findIndex((function (y) {
                                          return Caml_obj.caml_equal(y, x);
                                        }), availablePackageManagers$1) !== undefined;
                          }), alreadyUsedPackageManagers$1);
                    if (_multipleChoices) {
                      if (_multipleChoices[1]) {
                        var config = Vscode.workspace.getConfiguration("ocaml");
                        var match = config.packageManager;
                        var match$1 = config.toolChainRoot;
                        if (match == null) {
                          return Promise.resolve(/* Error */Block.__(1, ["TODO: Implement prompting choice of package manager"]));
                        } else if (match$1 == null) {
                          return ofName(env, match, projectRoot, projectRoot);
                        } else {
                          return ofName(env, match, match$1, projectRoot);
                        }
                      } else {
                        var match$2 = _multipleChoices[0];
                        var env$1 = env;
                        var root = match$2[1];
                        var discoveredManifestPath = projectRoot;
                        var t = match$2[0];
                        if (t) {
                          return make$1(env$1, root, discoveredManifestPath);
                        } else {
                          return make$2(env$1, root, discoveredManifestPath);
                        }
                      }
                    } else {
                      return Promise.resolve(/* Error */Block.__(1, [" No package manager found. We support opam (https://opam.ocaml.org/) and esy (https://esy.sh/) "]));
                    }
                  })));
}

function setup(param) {
  var projectRoot = param.projectRoot;
  var spec = param.spec;
  return Curry._1(spec.setup, /* () */0).then((function (param) {
                    if (param.tag) {
                      return Promise.resolve(/* Error */Block.__(1, [param[0]]));
                    } else {
                      return Curry._1(spec.env, /* () */0);
                    }
                  })).then((function (param) {
                  if (param.tag) {
                    return Promise.resolve(Result.fail(param[0]));
                  } else {
                    return make(param[0], "ocamllsp");
                  }
                })).then((function (param) {
                return Utils.$less$less((function (prim) {
                              return Promise.resolve(prim);
                            }), (function (param) {
                              if (param.tag) {
                                return /* Error */Block.__(1, [" Toolchain initialisation failed: " + (String(param[0]) + " ")]);
                              } else {
                                return /* Ok */Block.__(0, [{
                                            spec: spec,
                                            projectRoot: projectRoot
                                          }]);
                              }
                            }), param);
              }));
}

function lsp(t) {
  return Curry._1(t.spec.lsp, /* () */0);
}

exports.init = init;
exports.setup = setup;
exports.lsp = lsp;
/* lockFile Not a pure module */
