name: Dependency Analysis

on:
  - push

concurrency:
  group: dependency-analysis
  cancel-in-progress: false

permissions: read-all

jobs:
  opam-dependency-submission:
    name: Opam Dependency Submission

    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout tree
        uses: actions/checkout@v4

      - name: Set-up OCaml 4.14
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: "4.14"
          allow-prerelease-opam: true

      - name: Opam Dependency Submission
        uses: ocaml/setup-ocaml/analysis@analysis

  dependency-review:
    name: Dependency Review

    if: github.event_name == 'pull_request'

    needs:
      - opam-dependency-submission

    runs-on: ubuntu-latest

    steps:
      - name: Checkout tree
        uses: actions/checkout@v4

      - name: Dependency Review
        uses: actions/dependency-review-action@v3
