name: Dependency Review

on: pull_request

permissions: read-all

jobs:
  dependency-review:
    name: Dependency Review
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tree
        uses: actions/checkout@v5
      - name: Dependency Review
        uses: actions/dependency-review-action@v4
