name: Opam Dependency Submission

on:
  push:
    branches:
      - master

concurrency:
  group: opam-dependency-submission
  cancel-in-progress: true

permissions: read-all

jobs:
  opam-dependency-submission:
    name: Opam Dependency Submission

    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout tree
        uses: actions/checkout@v4

      - name: Set-up Mold
        uses: rui314/setup-mold@v1

      - name: Set-up OCaml 4.14
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: "4.14"
          allow-prerelease-opam: true

      - name: Opam Dependency Submission
        uses: ocaml/setup-ocaml/analysis@v2
